### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by houxiaolinzhengdan** [SlicerDMRI/SupWMA#3]
Dear Zhang, I am Hou Xiaolin, a neurosurgeon from the Affiliated Hospital of Chengdu University of Traditional Chinese Medicine. I was lucky to see your Supwma study. I used your Git code. According to the instructions, there will be mistakes, I would like to ask you how to solve this problem, thank you. Is this a problem with the 3dslicer version?
![123456](https://user-images.githubusercontent.com/89176183/166090913-d20e77b0-59fe-401f-855a-e540d389a19d.png)

**Comment by tengfeixue-victor** [comment]
Hi Xiaolin,

Thanks for reporting this! Sorry for the inconvenience. It's not your problem. I fixed this bug. You can git clone the updated code and give a try again. Please let us know if you have any questions. 

Thanks,
Tengfei

**Comment by houxiaolinzhengdan** [comment]
thank you ,but i still have an other question.Statistical analysis of  fiber bundles was not available， Is this a problem with the 3dslicer version or a bug 
![Screenshot from 2022-05-02 23-46-45](https://user-images.githubusercontent.com/89176183/166266161-943e03ce-239c-4d12-a4b4-16d751cf580b.png)
?

**Comment by zhangfanmark** [comment]
Hi @houxiaolinzhengdan 

Please try:

wm_diffusion_measurements.py inputfolder outputcsv “Path_to_Sicer_executable/Slicer --launch FiberTractMeasurements”

In this way, the program will be able to load the related libraries. Note: please keep the quotes.

Regards,
Fan

**Comment by houxiaolinzhengdan** [comment]
Sorry to bother you again, I have followed your instructions, but there is still a problem. FiberTractMeasurements cannot be found, but  this file actually exist in 3DSLicer (it was available after version 4.11). I have changed several versions of 3Dslicer, but it still cannot be solved the problem. Could you please take a look at the problem, thank you very much.

**Comment by houxiaolinzhengdan** [comment]
Sorry to bother you again, I have followed your instructions, but there is still a problem. FiberTractMeasurements cannot be found, but this file actually exist in 3DSLicer (it was available after version 4.11). I have changed several versions of 3Dslicer, but it still cannot be solved the problem. Could you please take a look at the problem, thank you very much!
[Screenshot from 2022-05-04 09-55-39](https://user-images.githubusercontent.com/89176183/166614161-c0239c31-c302-402a-a1c3-53bb9e8c8fd0.png)

**Comment by zhangfanmark** [comment]
Hi,

Slicer 4.10.2 should work (Slicer 4.11 should also work). Please make sure that you have installed SlicerDMRI: http://dmri.slicer.org/download/

Regards,
Fan

**Comment by houxiaolinzhengdan** [comment]
i have tried the 3Dslicer 4.10.2 and install the SlicerDMRI, but it still not work!
![Screenshot from 2022-05-04 10-25-27](https://user-images.githubusercontent.com/89176183/166616879-b7d71918-532d-46b8-a9b1-0149c2b3b5d4.png)
![Screenshot from 2022-05-04 10-25-48](https://user-images.githubusercontent.com/89176183/166616909-5e80d677-a24f-4c2d-b383-e78e2653c508.png)

**Comment by zhangfanmark** [comment]
Not sure if this is true, but it seems the quotes are not in English. Can you try to change your keyboard input?

**Comment by houxiaolinzhengdan** [comment]
i have solve the problem. thank you very much! but i have another question, When I imported the segmented nerve fibers into 3Dslicer, the spatial position was incorrect, Is there a solution for the problem?
![Screenshot from 2022-05-04 11-22-06](https://user-images.githubusercontent.com/89176183/166619956-3eb68277-a378-46d0-b0c9-df8d82197789.png)

**Comment by tengfeixue-victor** [comment]
Hi, it seems you need to transfer the parcellation results back to the subject space. Please refer to the answer [here](https://github.com/SlicerDMRI/SupWMA/issues/1#issuecomment-1086559040) to if it helps.

If you have any questions, please feel free to let us know.

Thanks,
Tengfei
